apiVersion: v1
kind: Service
metadata:
  name: weather-api
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  weather-api
      prefix: /weather-api/
      service: weather-api:3015
spec:
  type: ClusterIP
  ports:
    - port: 3015
      targetPort: 3015
  selector:
    app: weather-api