apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-apiv2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-apiv2
  template:
    metadata:
      labels:
        app: data-apiv2
    spec:
      containers:
        - name: data-apiv2
          image: rubixacr.azurecr.io/kubewrkshp/dataapi:v26099
          imagePullPolicy: Always
          env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: cosmos-db-connect
                  key: user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cosmos-db-connect
                  key: password
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: appinsights
                  key: appinsights                   
      imagePullSecrets:
        - name: default.rubixacr