apiVersion: apps/v1
kind: Deployment
metadata:
  name: quakes-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quakes-api
  template:
    metadata:
      labels:
        app: quakes-api
    spec:
      containers:
        - name: quakes-api
          image: rubixacr.azurecr.io/kubewrkshp/quakesapi:v26023
          imagePullPolicy: Always
      imagePullSecrets:
        - name: rubixacr
apiVersion: v1
kind: Service
metadata:
  name: quakes-api
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: quakes-api