apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-tracker-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-tracker-ui
  template:
    metadata:
      labels:
        app: service-tracker-ui
    spec:
      containers:
        - name: service-tracker-ui
          image: rubixacr.azurecr.io/kubewrkshp/servicetrackerui:v26023
          imagePullPolicy: Always
          env:
            - name: FLIGHT_API_ROOT
              value: http://40.69.164.148:3003/
            - name: WEATHER_API_ROOT
              value: http://weather-api.hackfest.svc.cluster.local:3015/
            - name: QUAKES_API_ROOT
              value: http://52.176.90.85:3012/
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: appinsights
                  key: appinsights
      imagePullSecrets:
        - name: rubixacr
