apiVersion: v1
kind: Service
metadata:
  name: service-tracker-ui
  annotations:
    getambassador.io/config: |
      ---
        apiVersion: ambassador/v1
        kind:  Mapping
        name:  service-tracker-ui
        prefix: /servicetracker/
        service: service-tracker-ui:8080
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: service-tracker-ui
